language: node_js
node_js: stable
dist: trusty
addons:
  sauce_connect: true
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
  - bower_components
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: TvIwaqes3argt7JDxjPDtNeoum1bk+fJ6iRrodiWKzhcuP8CLCsxe9ACBzaOkVnw6GrW9A+MpZngoq2gmOWV5X22gI9IpYWQzI7IjQlWKajXz3GyD8Q17U+t7sv4TyqPgk/PO/OcpuO3RBmzgcHyBdeNaqotqlpfeMSfJfVW4YCoJ6YMBsoJse4FQ0dOKGVxOOiA4PxeI47ZKaJPflvWqAoROasyc1ivSzUXsmEJmEuVJvCAf3GZX9D8hg7n9lyW+1C+heUpaoNSSTdect9PMmJpxy1uRHnxb161ApZ2WMxMTAQkSqZnWVc5+27EDXupuL0zaDUG3WQi684n1oGpbltuvB1uOqHgoFYI0Pw5Y1UD7gugoDKPn0ihuL3lL1QgCUiEh6PzOBfyfWAIwTXT2h90yPdTJF6FRRdPcAZ1VRCBB3gP93AJBRYRWzj0xeWjFvazgLTux/LSlxhTDhBOiMLwFL01Zq+nrYdFQ6oVDOo6L7iiK8NQ2p6KIJyfVFuM6Kl4I3f8tHYTBVD6am4l1KTCXpNITP7NArBMAL+HdQ6SOOsTcmxrKNn9FZoOKs2+m2+XCUYWkhjp0yNydUFTuBdZyQIAW5lvTjfnskpthztFipl20j7sDMm+/IqOd3G6iDl3FU2UKxfW/Tl5Ufw2B2zwOJWzvY26jDHg09PZTVM=
  - secure: VZMvoUUMyCEQrxA6P8z0Jy9n1cP321QqKSlouHwMnKXTso4mUjjn2bV3QzpwDLdKgPDIpQ5DbLHRVeIpcSNclTqSxaKwdbcbkluCk3uvZnXJl9JiSFtM1aiGKv/Dc+AvVrGrxsbG4ogPtInI0egZjmDaHAOvToe/g8ORDnhqAkSPMrf+RXrhTUFOXQwnfDxGV3yj6YHLCbDYbs7pPKWrfkNa0vf3Qx2pynvACO22oSGsZxOyyf2snCYSXr0Zglh6Ca6EwCqxIYGAbu8TDDjw25T4N/R9r+tQPFYPi3MM3LR74Zo+gUUQxtcfUATNqNSQmSvjfAAFOP9ltUrY3yzL0wtUqArcE3vFpwNDWS/rBiSNOi3UINMTI/fk42MSAKL9sXBZ/gYegOnNwiHPe0lWgPLowBc9iY9+M7dGknQ3aUbDnMb+DwpeGEsUir5M9y73QkHrKkPVXmrgUzWyoyV1mJAHPPIfqYhQksELO7O0Jwpti2mBX/4CyJ7HVVk+PHsXnPu/Od80oHB++Xf4d4o6WTZ22PFaeLfufhFoD3hqeOBAdjkxbMd1rauXSnQ49E/hegp8YonP4+PjLGI7SH3SncqjwmlWKz5NgE2Qb+1sDUBRDEeeaRONn8LNMvP4QwyWW7VNSPsuyfVpN5X/OHd5VEOrhCaoDr2bvF0BghxZuE8=
